CREATE TABLE [dbo].[DRP_SR]
(
	[DRPDID] INT NOT NULL, 
    [SRID] Int NOT NULL 
    PRIMARY KEY ([DRPDID],[SRID]), 
    [Amount] DECIMAL(18, 2) NULL, 
    [SRDID] INT NULL, 
    CONSTRAINT [FK_DRP_SR_SRdetails] FOREIGN KEY ([SRDID]) REFERENCES [SRdetails]([SRDID])

)
