CREATE TABLE [dbo].[SRUploads]
(
	[SRUID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [SRID] INT NULL, 
	[SRDID]      INT          NULL,
    [Path] VARCHAR(50) NULL, 
    [UploadName] VARCHAR(50) NULL,
	CONSTRAINT [FK_SRUploads_ToSR] FOREIGN KEY ([SRID]) REFERENCES [ServiceRequest]([SRID]),
    CONSTRAINT [FK_SRUploads_ToSRD] FOREIGN KEY ([SRDID]) REFERENCES [dbo].[SRdetails] ([SRDID]) 

)
